---
- name: Config VM
  hosts: prod
  gather_facts: false
  become: true
  remote_user: azureuser

  tasks:

  - name: Install apache
    ansible.builtin.apt:
      package:
        - apache2
      state: present
